package com.zpapi.other.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zpapi.other.model.GtCard;
import com.zpapi.other.model.GtCardExample;

public interface GtCardMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int countByExample(GtCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int deleteByExample(GtCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int insert(GtCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int insertSelective(GtCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	List<GtCard> selectByExample(GtCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	GtCard selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int updateByExampleSelective(@Param("record") GtCard record, @Param("example") GtCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int updateByExample(@Param("record") GtCard record, @Param("example") GtCardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int updateByPrimaryKeySelective(GtCard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	int updateByPrimaryKey(GtCard record);
}