package com.zpapi.other.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zpapi.other.model.GtCouponCardTask;
import com.zpapi.other.model.GtCouponCardTaskExample;

public interface GtCouponCardTaskMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int countByExample(GtCouponCardTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int deleteByExample(GtCouponCardTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int deleteByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int insert(GtCouponCardTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int insertSelective(GtCouponCardTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	List<GtCouponCardTask> selectByExample(GtCouponCardTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	GtCouponCardTask selectByPrimaryKey(Integer taskId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int updateByExampleSelective(@Param("record") GtCouponCardTask record,
			@Param("example") GtCouponCardTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int updateByExample(@Param("record") GtCouponCardTask record,
			@Param("example") GtCouponCardTaskExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int updateByPrimaryKeySelective(GtCouponCardTask record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	int updateByPrimaryKey(GtCouponCardTask record);
}