package com.zpapi.other.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.zpapi.other.model.OauthAccessToken;
import com.zpapi.other.model.OauthAccessTokenExample;
import com.zpapi.other.model.OauthAccessTokenWithBLOBs;

public interface OauthAccessTokenMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int countByExample(OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int deleteByExample(OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int insert(OauthAccessTokenWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int insertSelective(OauthAccessTokenWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	List<OauthAccessTokenWithBLOBs> selectByExampleWithBLOBs(OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	List<OauthAccessToken> selectByExample(OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int updateByExampleSelective(@Param("record") OauthAccessTokenWithBLOBs record,
			@Param("example") OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") OauthAccessTokenWithBLOBs record,
			@Param("example") OauthAccessTokenExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table oauth_access_token
	 *
	 * @mbggenerated Fri Apr 01 19:51:55 CST 2016
	 */
	int updateByExample(@Param("record") OauthAccessToken record,
			@Param("example") OauthAccessTokenExample example);
}