package com.zpapi.other.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GtCardExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public GtCardExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdIsNull() {
			addCriterion("card_batch_id is null");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdIsNotNull() {
			addCriterion("card_batch_id is not null");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdEqualTo(Integer value) {
			addCriterion("card_batch_id =", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdNotEqualTo(Integer value) {
			addCriterion("card_batch_id <>", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdGreaterThan(Integer value) {
			addCriterion("card_batch_id >", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("card_batch_id >=", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdLessThan(Integer value) {
			addCriterion("card_batch_id <", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdLessThanOrEqualTo(Integer value) {
			addCriterion("card_batch_id <=", value, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdIn(List<Integer> values) {
			addCriterion("card_batch_id in", values, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdNotIn(List<Integer> values) {
			addCriterion("card_batch_id not in", values, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdBetween(Integer value1, Integer value2) {
			addCriterion("card_batch_id between", value1, value2, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andCardBatchIdNotBetween(Integer value1, Integer value2) {
			addCriterion("card_batch_id not between", value1, value2, "cardBatchId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCardNumberIsNull() {
			addCriterion("card_number is null");
			return (Criteria) this;
		}

		public Criteria andCardNumberIsNotNull() {
			addCriterion("card_number is not null");
			return (Criteria) this;
		}

		public Criteria andCardNumberEqualTo(String value) {
			addCriterion("card_number =", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberNotEqualTo(String value) {
			addCriterion("card_number <>", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberGreaterThan(String value) {
			addCriterion("card_number >", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberGreaterThanOrEqualTo(String value) {
			addCriterion("card_number >=", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberLessThan(String value) {
			addCriterion("card_number <", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberLessThanOrEqualTo(String value) {
			addCriterion("card_number <=", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberLike(String value) {
			addCriterion("card_number like", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberNotLike(String value) {
			addCriterion("card_number not like", value, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberIn(List<String> values) {
			addCriterion("card_number in", values, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberNotIn(List<String> values) {
			addCriterion("card_number not in", values, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberBetween(String value1, String value2) {
			addCriterion("card_number between", value1, value2, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andCardNumberNotBetween(String value1, String value2) {
			addCriterion("card_number not between", value1, value2, "cardNumber");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Integer value) {
			addCriterion("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Integer value) {
			addCriterion("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Integer value) {
			addCriterion("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Integer value) {
			addCriterion("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Integer value) {
			addCriterion("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Integer> values) {
			addCriterion("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Integer> values) {
			addCriterion("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Integer value1, Integer value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Integer value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Integer value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Integer value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Integer value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Integer value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Integer> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Integer> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Integer value1, Integer value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Integer value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Integer value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Integer value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Integer value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Integer> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Integer> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeIsNull() {
			addCriterion("active_time is null");
			return (Criteria) this;
		}

		public Criteria andActiveTimeIsNotNull() {
			addCriterion("active_time is not null");
			return (Criteria) this;
		}

		public Criteria andActiveTimeEqualTo(Integer value) {
			addCriterion("active_time =", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeNotEqualTo(Integer value) {
			addCriterion("active_time <>", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeGreaterThan(Integer value) {
			addCriterion("active_time >", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("active_time >=", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeLessThan(Integer value) {
			addCriterion("active_time <", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeLessThanOrEqualTo(Integer value) {
			addCriterion("active_time <=", value, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeIn(List<Integer> values) {
			addCriterion("active_time in", values, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeNotIn(List<Integer> values) {
			addCriterion("active_time not in", values, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeBetween(Integer value1, Integer value2) {
			addCriterion("active_time between", value1, value2, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("active_time not between", value1, value2, "activeTime");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdIsNull() {
			addCriterion("active_member_id is null");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdIsNotNull() {
			addCriterion("active_member_id is not null");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdEqualTo(Integer value) {
			addCriterion("active_member_id =", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdNotEqualTo(Integer value) {
			addCriterion("active_member_id <>", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdGreaterThan(Integer value) {
			addCriterion("active_member_id >", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("active_member_id >=", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdLessThan(Integer value) {
			addCriterion("active_member_id <", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdLessThanOrEqualTo(Integer value) {
			addCriterion("active_member_id <=", value, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdIn(List<Integer> values) {
			addCriterion("active_member_id in", values, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdNotIn(List<Integer> values) {
			addCriterion("active_member_id not in", values, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdBetween(Integer value1, Integer value2) {
			addCriterion("active_member_id between", value1, value2, "activeMemberId");
			return (Criteria) this;
		}

		public Criteria andActiveMemberIdNotBetween(Integer value1, Integer value2) {
			addCriterion("active_member_id not between", value1, value2, "activeMemberId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Apr 01 20:18:33 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card
	 *
	 * @mbggenerated Fri Apr 01 20:18:33 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}