package com.zpapi.other.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GtCardBatchExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public GtCardBatchExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andBatchIsNull() {
			addCriterion("batch is null");
			return (Criteria) this;
		}

		public Criteria andBatchIsNotNull() {
			addCriterion("batch is not null");
			return (Criteria) this;
		}

		public Criteria andBatchEqualTo(Long value) {
			addCriterion("batch =", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotEqualTo(Long value) {
			addCriterion("batch <>", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchGreaterThan(Long value) {
			addCriterion("batch >", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchGreaterThanOrEqualTo(Long value) {
			addCriterion("batch >=", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchLessThan(Long value) {
			addCriterion("batch <", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchLessThanOrEqualTo(Long value) {
			addCriterion("batch <=", value, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchIn(List<Long> values) {
			addCriterion("batch in", values, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotIn(List<Long> values) {
			addCriterion("batch not in", values, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchBetween(Long value1, Long value2) {
			addCriterion("batch between", value1, value2, "batch");
			return (Criteria) this;
		}

		public Criteria andBatchNotBetween(Long value1, Long value2) {
			addCriterion("batch not between", value1, value2, "batch");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andNumberIsNull() {
			addCriterion("number is null");
			return (Criteria) this;
		}

		public Criteria andNumberIsNotNull() {
			addCriterion("number is not null");
			return (Criteria) this;
		}

		public Criteria andNumberEqualTo(Integer value) {
			addCriterion("number =", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotEqualTo(Integer value) {
			addCriterion("number <>", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThan(Integer value) {
			addCriterion("number >", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("number >=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThan(Integer value) {
			addCriterion("number <", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberLessThanOrEqualTo(Integer value) {
			addCriterion("number <=", value, "number");
			return (Criteria) this;
		}

		public Criteria andNumberIn(List<Integer> values) {
			addCriterion("number in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotIn(List<Integer> values) {
			addCriterion("number not in", values, "number");
			return (Criteria) this;
		}

		public Criteria andNumberBetween(Integer value1, Integer value2) {
			addCriterion("number between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("number not between", value1, value2, "number");
			return (Criteria) this;
		}

		public Criteria andCardPrefixIsNull() {
			addCriterion("card_prefix is null");
			return (Criteria) this;
		}

		public Criteria andCardPrefixIsNotNull() {
			addCriterion("card_prefix is not null");
			return (Criteria) this;
		}

		public Criteria andCardPrefixEqualTo(String value) {
			addCriterion("card_prefix =", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixNotEqualTo(String value) {
			addCriterion("card_prefix <>", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixGreaterThan(String value) {
			addCriterion("card_prefix >", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixGreaterThanOrEqualTo(String value) {
			addCriterion("card_prefix >=", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixLessThan(String value) {
			addCriterion("card_prefix <", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixLessThanOrEqualTo(String value) {
			addCriterion("card_prefix <=", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixLike(String value) {
			addCriterion("card_prefix like", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixNotLike(String value) {
			addCriterion("card_prefix not like", value, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixIn(List<String> values) {
			addCriterion("card_prefix in", values, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixNotIn(List<String> values) {
			addCriterion("card_prefix not in", values, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixBetween(String value1, String value2) {
			addCriterion("card_prefix between", value1, value2, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andCardPrefixNotBetween(String value1, String value2) {
			addCriterion("card_prefix not between", value1, value2, "cardPrefix");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(BigDecimal value) {
			addCriterion("amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(BigDecimal value) {
			addCriterion("amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(BigDecimal value) {
			addCriterion("amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(BigDecimal value) {
			addCriterion("amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(BigDecimal value) {
			addCriterion("amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<BigDecimal> values) {
			addCriterion("amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<BigDecimal> values) {
			addCriterion("amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIsNull() {
			addCriterion("validity_period_type is null");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIsNotNull() {
			addCriterion("validity_period_type is not null");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeEqualTo(Boolean value) {
			addCriterion("validity_period_type =", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotEqualTo(Boolean value) {
			addCriterion("validity_period_type <>", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeGreaterThan(Boolean value) {
			addCriterion("validity_period_type >", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("validity_period_type >=", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeLessThan(Boolean value) {
			addCriterion("validity_period_type <", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("validity_period_type <=", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIn(List<Boolean> values) {
			addCriterion("validity_period_type in", values, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotIn(List<Boolean> values) {
			addCriterion("validity_period_type not in", values, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("validity_period_type between", value1, value2, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("validity_period_type not between", value1, value2, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNull() {
			addCriterion("start_time is null");
			return (Criteria) this;
		}

		public Criteria andStartTimeIsNotNull() {
			addCriterion("start_time is not null");
			return (Criteria) this;
		}

		public Criteria andStartTimeEqualTo(Integer value) {
			addCriterion("start_time =", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotEqualTo(Integer value) {
			addCriterion("start_time <>", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThan(Integer value) {
			addCriterion("start_time >", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("start_time >=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThan(Integer value) {
			addCriterion("start_time <", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeLessThanOrEqualTo(Integer value) {
			addCriterion("start_time <=", value, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeIn(List<Integer> values) {
			addCriterion("start_time in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotIn(List<Integer> values) {
			addCriterion("start_time not in", values, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeBetween(Integer value1, Integer value2) {
			addCriterion("start_time between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andStartTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("start_time not between", value1, value2, "startTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Integer value) {
			addCriterion("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Integer value) {
			addCriterion("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Integer value) {
			addCriterion("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Integer value) {
			addCriterion("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Integer value) {
			addCriterion("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Integer> values) {
			addCriterion("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Integer> values) {
			addCriterion("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Integer value1, Integer value2) {
			addCriterion("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNull() {
			addCriterion("valid_time is null");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNotNull() {
			addCriterion("valid_time is not null");
			return (Criteria) this;
		}

		public Criteria andValidTimeEqualTo(Integer value) {
			addCriterion("valid_time =", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotEqualTo(Integer value) {
			addCriterion("valid_time <>", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThan(Integer value) {
			addCriterion("valid_time >", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("valid_time >=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThan(Integer value) {
			addCriterion("valid_time <", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThanOrEqualTo(Integer value) {
			addCriterion("valid_time <=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeIn(List<Integer> values) {
			addCriterion("valid_time in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotIn(List<Integer> values) {
			addCriterion("valid_time not in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeBetween(Integer value1, Integer value2) {
			addCriterion("valid_time between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("valid_time not between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRuleTextIsNull() {
			addCriterion("rule_text is null");
			return (Criteria) this;
		}

		public Criteria andRuleTextIsNotNull() {
			addCriterion("rule_text is not null");
			return (Criteria) this;
		}

		public Criteria andRuleTextEqualTo(String value) {
			addCriterion("rule_text =", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextNotEqualTo(String value) {
			addCriterion("rule_text <>", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextGreaterThan(String value) {
			addCriterion("rule_text >", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextGreaterThanOrEqualTo(String value) {
			addCriterion("rule_text >=", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextLessThan(String value) {
			addCriterion("rule_text <", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextLessThanOrEqualTo(String value) {
			addCriterion("rule_text <=", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextLike(String value) {
			addCriterion("rule_text like", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextNotLike(String value) {
			addCriterion("rule_text not like", value, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextIn(List<String> values) {
			addCriterion("rule_text in", values, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextNotIn(List<String> values) {
			addCriterion("rule_text not in", values, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextBetween(String value1, String value2) {
			addCriterion("rule_text between", value1, value2, "ruleText");
			return (Criteria) this;
		}

		public Criteria andRuleTextNotBetween(String value1, String value2) {
			addCriterion("rule_text not between", value1, value2, "ruleText");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionIsNull() {
			addCriterion("is_condition_reduction is null");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionIsNotNull() {
			addCriterion("is_condition_reduction is not null");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionEqualTo(Integer value) {
			addCriterion("is_condition_reduction =", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionNotEqualTo(Integer value) {
			addCriterion("is_condition_reduction <>", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionGreaterThan(Integer value) {
			addCriterion("is_condition_reduction >", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_condition_reduction >=", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionLessThan(Integer value) {
			addCriterion("is_condition_reduction <", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionLessThanOrEqualTo(Integer value) {
			addCriterion("is_condition_reduction <=", value, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionIn(List<Integer> values) {
			addCriterion("is_condition_reduction in", values, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionNotIn(List<Integer> values) {
			addCriterion("is_condition_reduction not in", values, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionBetween(Integer value1, Integer value2) {
			addCriterion("is_condition_reduction between", value1, value2, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsConditionReductionNotBetween(Integer value1, Integer value2) {
			addCriterion("is_condition_reduction not between", value1, value2, "isConditionReduction");
			return (Criteria) this;
		}

		public Criteria andIsDiscountIsNull() {
			addCriterion("is_discount is null");
			return (Criteria) this;
		}

		public Criteria andIsDiscountIsNotNull() {
			addCriterion("is_discount is not null");
			return (Criteria) this;
		}

		public Criteria andIsDiscountEqualTo(Integer value) {
			addCriterion("is_discount =", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountNotEqualTo(Integer value) {
			addCriterion("is_discount <>", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountGreaterThan(Integer value) {
			addCriterion("is_discount >", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_discount >=", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountLessThan(Integer value) {
			addCriterion("is_discount <", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountLessThanOrEqualTo(Integer value) {
			addCriterion("is_discount <=", value, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountIn(List<Integer> values) {
			addCriterion("is_discount in", values, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountNotIn(List<Integer> values) {
			addCriterion("is_discount not in", values, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountBetween(Integer value1, Integer value2) {
			addCriterion("is_discount between", value1, value2, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsDiscountNotBetween(Integer value1, Integer value2) {
			addCriterion("is_discount not between", value1, value2, "isDiscount");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardIsNull() {
			addCriterion("is_gift_card is null");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardIsNotNull() {
			addCriterion("is_gift_card is not null");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardEqualTo(Integer value) {
			addCriterion("is_gift_card =", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardNotEqualTo(Integer value) {
			addCriterion("is_gift_card <>", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardGreaterThan(Integer value) {
			addCriterion("is_gift_card >", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_gift_card >=", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardLessThan(Integer value) {
			addCriterion("is_gift_card <", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardLessThanOrEqualTo(Integer value) {
			addCriterion("is_gift_card <=", value, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardIn(List<Integer> values) {
			addCriterion("is_gift_card in", values, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardNotIn(List<Integer> values) {
			addCriterion("is_gift_card not in", values, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardBetween(Integer value1, Integer value2) {
			addCriterion("is_gift_card between", value1, value2, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsGiftCardNotBetween(Integer value1, Integer value2) {
			addCriterion("is_gift_card not between", value1, value2, "isGiftCard");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponIsNull() {
			addCriterion("is_return_coupon is null");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponIsNotNull() {
			addCriterion("is_return_coupon is not null");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponEqualTo(Integer value) {
			addCriterion("is_return_coupon =", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponNotEqualTo(Integer value) {
			addCriterion("is_return_coupon <>", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponGreaterThan(Integer value) {
			addCriterion("is_return_coupon >", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_return_coupon >=", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponLessThan(Integer value) {
			addCriterion("is_return_coupon <", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponLessThanOrEqualTo(Integer value) {
			addCriterion("is_return_coupon <=", value, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponIn(List<Integer> values) {
			addCriterion("is_return_coupon in", values, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponNotIn(List<Integer> values) {
			addCriterion("is_return_coupon not in", values, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponBetween(Integer value1, Integer value2) {
			addCriterion("is_return_coupon between", value1, value2, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsReturnCouponNotBetween(Integer value1, Integer value2) {
			addCriterion("is_return_coupon not between", value1, value2, "isReturnCoupon");
			return (Criteria) this;
		}

		public Criteria andIsGeneralIsNull() {
			addCriterion("is_general is null");
			return (Criteria) this;
		}

		public Criteria andIsGeneralIsNotNull() {
			addCriterion("is_general is not null");
			return (Criteria) this;
		}

		public Criteria andIsGeneralEqualTo(Integer value) {
			addCriterion("is_general =", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralNotEqualTo(Integer value) {
			addCriterion("is_general <>", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralGreaterThan(Integer value) {
			addCriterion("is_general >", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_general >=", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralLessThan(Integer value) {
			addCriterion("is_general <", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralLessThanOrEqualTo(Integer value) {
			addCriterion("is_general <=", value, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralIn(List<Integer> values) {
			addCriterion("is_general in", values, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralNotIn(List<Integer> values) {
			addCriterion("is_general not in", values, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralBetween(Integer value1, Integer value2) {
			addCriterion("is_general between", value1, value2, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsGeneralNotBetween(Integer value1, Integer value2) {
			addCriterion("is_general not between", value1, value2, "isGeneral");
			return (Criteria) this;
		}

		public Criteria andIsIncludeIsNull() {
			addCriterion("is_include is null");
			return (Criteria) this;
		}

		public Criteria andIsIncludeIsNotNull() {
			addCriterion("is_include is not null");
			return (Criteria) this;
		}

		public Criteria andIsIncludeEqualTo(Integer value) {
			addCriterion("is_include =", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeNotEqualTo(Integer value) {
			addCriterion("is_include <>", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeGreaterThan(Integer value) {
			addCriterion("is_include >", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_include >=", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeLessThan(Integer value) {
			addCriterion("is_include <", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeLessThanOrEqualTo(Integer value) {
			addCriterion("is_include <=", value, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeIn(List<Integer> values) {
			addCriterion("is_include in", values, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeNotIn(List<Integer> values) {
			addCriterion("is_include not in", values, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeBetween(Integer value1, Integer value2) {
			addCriterion("is_include between", value1, value2, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsIncludeNotBetween(Integer value1, Integer value2) {
			addCriterion("is_include not between", value1, value2, "isInclude");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreIsNull() {
			addCriterion("is_send_score is null");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreIsNotNull() {
			addCriterion("is_send_score is not null");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreEqualTo(Integer value) {
			addCriterion("is_send_score =", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreNotEqualTo(Integer value) {
			addCriterion("is_send_score <>", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreGreaterThan(Integer value) {
			addCriterion("is_send_score >", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_send_score >=", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreLessThan(Integer value) {
			addCriterion("is_send_score <", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreLessThanOrEqualTo(Integer value) {
			addCriterion("is_send_score <=", value, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreIn(List<Integer> values) {
			addCriterion("is_send_score in", values, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreNotIn(List<Integer> values) {
			addCriterion("is_send_score not in", values, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreBetween(Integer value1, Integer value2) {
			addCriterion("is_send_score between", value1, value2, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andIsSendScoreNotBetween(Integer value1, Integer value2) {
			addCriterion("is_send_score not between", value1, value2, "isSendScore");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeIsNull() {
			addCriterion("supplier_type is null");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeIsNotNull() {
			addCriterion("supplier_type is not null");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeEqualTo(Integer value) {
			addCriterion("supplier_type =", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeNotEqualTo(Integer value) {
			addCriterion("supplier_type <>", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeGreaterThan(Integer value) {
			addCriterion("supplier_type >", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("supplier_type >=", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeLessThan(Integer value) {
			addCriterion("supplier_type <", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeLessThanOrEqualTo(Integer value) {
			addCriterion("supplier_type <=", value, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeIn(List<Integer> values) {
			addCriterion("supplier_type in", values, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeNotIn(List<Integer> values) {
			addCriterion("supplier_type not in", values, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeBetween(Integer value1, Integer value2) {
			addCriterion("supplier_type between", value1, value2, "supplierType");
			return (Criteria) this;
		}

		public Criteria andSupplierTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("supplier_type not between", value1, value2, "supplierType");
			return (Criteria) this;
		}

		public Criteria andUseConditionIsNull() {
			addCriterion("use_condition is null");
			return (Criteria) this;
		}

		public Criteria andUseConditionIsNotNull() {
			addCriterion("use_condition is not null");
			return (Criteria) this;
		}

		public Criteria andUseConditionEqualTo(Integer value) {
			addCriterion("use_condition =", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotEqualTo(Integer value) {
			addCriterion("use_condition <>", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionGreaterThan(Integer value) {
			addCriterion("use_condition >", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionGreaterThanOrEqualTo(Integer value) {
			addCriterion("use_condition >=", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionLessThan(Integer value) {
			addCriterion("use_condition <", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionLessThanOrEqualTo(Integer value) {
			addCriterion("use_condition <=", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionIn(List<Integer> values) {
			addCriterion("use_condition in", values, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotIn(List<Integer> values) {
			addCriterion("use_condition not in", values, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionBetween(Integer value1, Integer value2) {
			addCriterion("use_condition between", value1, value2, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotBetween(Integer value1, Integer value2) {
			addCriterion("use_condition not between", value1, value2, "useCondition");
			return (Criteria) this;
		}

		public Criteria andPartnerIdIsNull() {
			addCriterion("partner_id is null");
			return (Criteria) this;
		}

		public Criteria andPartnerIdIsNotNull() {
			addCriterion("partner_id is not null");
			return (Criteria) this;
		}

		public Criteria andPartnerIdEqualTo(Integer value) {
			addCriterion("partner_id =", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdNotEqualTo(Integer value) {
			addCriterion("partner_id <>", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdGreaterThan(Integer value) {
			addCriterion("partner_id >", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("partner_id >=", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdLessThan(Integer value) {
			addCriterion("partner_id <", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdLessThanOrEqualTo(Integer value) {
			addCriterion("partner_id <=", value, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdIn(List<Integer> values) {
			addCriterion("partner_id in", values, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdNotIn(List<Integer> values) {
			addCriterion("partner_id not in", values, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdBetween(Integer value1, Integer value2) {
			addCriterion("partner_id between", value1, value2, "partnerId");
			return (Criteria) this;
		}

		public Criteria andPartnerIdNotBetween(Integer value1, Integer value2) {
			addCriterion("partner_id not between", value1, value2, "partnerId");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationIsNull() {
			addCriterion("is_batch_accumulation is null");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationIsNotNull() {
			addCriterion("is_batch_accumulation is not null");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationEqualTo(Integer value) {
			addCriterion("is_batch_accumulation =", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationNotEqualTo(Integer value) {
			addCriterion("is_batch_accumulation <>", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationGreaterThan(Integer value) {
			addCriterion("is_batch_accumulation >", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationGreaterThanOrEqualTo(Integer value) {
			addCriterion("is_batch_accumulation >=", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationLessThan(Integer value) {
			addCriterion("is_batch_accumulation <", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationLessThanOrEqualTo(Integer value) {
			addCriterion("is_batch_accumulation <=", value, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationIn(List<Integer> values) {
			addCriterion("is_batch_accumulation in", values, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationNotIn(List<Integer> values) {
			addCriterion("is_batch_accumulation not in", values, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationBetween(Integer value1, Integer value2) {
			addCriterion("is_batch_accumulation between", value1, value2, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andIsBatchAccumulationNotBetween(Integer value1, Integer value2) {
			addCriterion("is_batch_accumulation not between", value1, value2, "isBatchAccumulation");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdIsNull() {
			addCriterion("apply_users_id is null");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdIsNotNull() {
			addCriterion("apply_users_id is not null");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdEqualTo(Integer value) {
			addCriterion("apply_users_id =", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdNotEqualTo(Integer value) {
			addCriterion("apply_users_id <>", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdGreaterThan(Integer value) {
			addCriterion("apply_users_id >", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("apply_users_id >=", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdLessThan(Integer value) {
			addCriterion("apply_users_id <", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdLessThanOrEqualTo(Integer value) {
			addCriterion("apply_users_id <=", value, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdIn(List<Integer> values) {
			addCriterion("apply_users_id in", values, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdNotIn(List<Integer> values) {
			addCriterion("apply_users_id not in", values, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdBetween(Integer value1, Integer value2) {
			addCriterion("apply_users_id between", value1, value2, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyUsersIdNotBetween(Integer value1, Integer value2) {
			addCriterion("apply_users_id not between", value1, value2, "applyUsersId");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNull() {
			addCriterion("apply_time is null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIsNotNull() {
			addCriterion("apply_time is not null");
			return (Criteria) this;
		}

		public Criteria andApplyTimeEqualTo(Integer value) {
			addCriterion("apply_time =", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotEqualTo(Integer value) {
			addCriterion("apply_time <>", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThan(Integer value) {
			addCriterion("apply_time >", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("apply_time >=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThan(Integer value) {
			addCriterion("apply_time <", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeLessThanOrEqualTo(Integer value) {
			addCriterion("apply_time <=", value, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeIn(List<Integer> values) {
			addCriterion("apply_time in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotIn(List<Integer> values) {
			addCriterion("apply_time not in", values, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeBetween(Integer value1, Integer value2) {
			addCriterion("apply_time between", value1, value2, "applyTime");
			return (Criteria) this;
		}

		public Criteria andApplyTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("apply_time not between", value1, value2, "applyTime");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdIsNull() {
			addCriterion("review_users_id is null");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdIsNotNull() {
			addCriterion("review_users_id is not null");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdEqualTo(Integer value) {
			addCriterion("review_users_id =", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdNotEqualTo(Integer value) {
			addCriterion("review_users_id <>", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdGreaterThan(Integer value) {
			addCriterion("review_users_id >", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("review_users_id >=", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdLessThan(Integer value) {
			addCriterion("review_users_id <", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdLessThanOrEqualTo(Integer value) {
			addCriterion("review_users_id <=", value, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdIn(List<Integer> values) {
			addCriterion("review_users_id in", values, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdNotIn(List<Integer> values) {
			addCriterion("review_users_id not in", values, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdBetween(Integer value1, Integer value2) {
			addCriterion("review_users_id between", value1, value2, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewUsersIdNotBetween(Integer value1, Integer value2) {
			addCriterion("review_users_id not between", value1, value2, "reviewUsersId");
			return (Criteria) this;
		}

		public Criteria andReviewTimeIsNull() {
			addCriterion("review_time is null");
			return (Criteria) this;
		}

		public Criteria andReviewTimeIsNotNull() {
			addCriterion("review_time is not null");
			return (Criteria) this;
		}

		public Criteria andReviewTimeEqualTo(Integer value) {
			addCriterion("review_time =", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeNotEqualTo(Integer value) {
			addCriterion("review_time <>", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeGreaterThan(Integer value) {
			addCriterion("review_time >", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("review_time >=", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeLessThan(Integer value) {
			addCriterion("review_time <", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeLessThanOrEqualTo(Integer value) {
			addCriterion("review_time <=", value, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeIn(List<Integer> values) {
			addCriterion("review_time in", values, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeNotIn(List<Integer> values) {
			addCriterion("review_time not in", values, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeBetween(Integer value1, Integer value2) {
			addCriterion("review_time between", value1, value2, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andReviewTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("review_time not between", value1, value2, "reviewTime");
			return (Criteria) this;
		}

		public Criteria andChannelUserIsNull() {
			addCriterion("channel_user is null");
			return (Criteria) this;
		}

		public Criteria andChannelUserIsNotNull() {
			addCriterion("channel_user is not null");
			return (Criteria) this;
		}

		public Criteria andChannelUserEqualTo(String value) {
			addCriterion("channel_user =", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotEqualTo(String value) {
			addCriterion("channel_user <>", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserGreaterThan(String value) {
			addCriterion("channel_user >", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserGreaterThanOrEqualTo(String value) {
			addCriterion("channel_user >=", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLessThan(String value) {
			addCriterion("channel_user <", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLessThanOrEqualTo(String value) {
			addCriterion("channel_user <=", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLike(String value) {
			addCriterion("channel_user like", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotLike(String value) {
			addCriterion("channel_user not like", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserIn(List<String> values) {
			addCriterion("channel_user in", values, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotIn(List<String> values) {
			addCriterion("channel_user not in", values, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserBetween(String value1, String value2) {
			addCriterion("channel_user between", value1, value2, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotBetween(String value1, String value2) {
			addCriterion("channel_user not between", value1, value2, "channelUser");
			return (Criteria) this;
		}

		public Criteria andScopeIsNull() {
			addCriterion("scope is null");
			return (Criteria) this;
		}

		public Criteria andScopeIsNotNull() {
			addCriterion("scope is not null");
			return (Criteria) this;
		}

		public Criteria andScopeEqualTo(Boolean value) {
			addCriterion("scope =", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotEqualTo(Boolean value) {
			addCriterion("scope <>", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeGreaterThan(Boolean value) {
			addCriterion("scope >", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("scope >=", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeLessThan(Boolean value) {
			addCriterion("scope <", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeLessThanOrEqualTo(Boolean value) {
			addCriterion("scope <=", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeIn(List<Boolean> values) {
			addCriterion("scope in", values, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotIn(List<Boolean> values) {
			addCriterion("scope not in", values, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeBetween(Boolean value1, Boolean value2) {
			addCriterion("scope between", value1, value2, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("scope not between", value1, value2, "scope");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIsNull() {
			addCriterion("use_range_detail is null");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIsNotNull() {
			addCriterion("use_range_detail is not null");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailEqualTo(String value) {
			addCriterion("use_range_detail =", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotEqualTo(String value) {
			addCriterion("use_range_detail <>", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailGreaterThan(String value) {
			addCriterion("use_range_detail >", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailGreaterThanOrEqualTo(String value) {
			addCriterion("use_range_detail >=", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLessThan(String value) {
			addCriterion("use_range_detail <", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLessThanOrEqualTo(String value) {
			addCriterion("use_range_detail <=", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLike(String value) {
			addCriterion("use_range_detail like", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotLike(String value) {
			addCriterion("use_range_detail not like", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIn(List<String> values) {
			addCriterion("use_range_detail in", values, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotIn(List<String> values) {
			addCriterion("use_range_detail not in", values, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailBetween(String value1, String value2) {
			addCriterion("use_range_detail between", value1, value2, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotBetween(String value1, String value2) {
			addCriterion("use_range_detail not between", value1, value2, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIsNull() {
			addCriterion("use_condition_detail is null");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIsNotNull() {
			addCriterion("use_condition_detail is not null");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailEqualTo(String value) {
			addCriterion("use_condition_detail =", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotEqualTo(String value) {
			addCriterion("use_condition_detail <>", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailGreaterThan(String value) {
			addCriterion("use_condition_detail >", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailGreaterThanOrEqualTo(String value) {
			addCriterion("use_condition_detail >=", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLessThan(String value) {
			addCriterion("use_condition_detail <", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLessThanOrEqualTo(String value) {
			addCriterion("use_condition_detail <=", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLike(String value) {
			addCriterion("use_condition_detail like", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotLike(String value) {
			addCriterion("use_condition_detail not like", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIn(List<String> values) {
			addCriterion("use_condition_detail in", values, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotIn(List<String> values) {
			addCriterion("use_condition_detail not in", values, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailBetween(String value1, String value2) {
			addCriterion("use_condition_detail between", value1, value2, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotBetween(String value1, String value2) {
			addCriterion("use_condition_detail not between", value1, value2, "useConditionDetail");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Apr 01 20:18:14 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_card_batch
	 *
	 * @mbggenerated Fri Apr 01 20:18:14 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}