package com.zpapi.other.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class GtCouponCardTaskExample {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	protected String orderByClause;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	protected boolean distinct;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public GtCouponCardTaskExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_id is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_id is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(Integer value) {
			addCriterion("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(Integer value) {
			addCriterion("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(Integer value) {
			addCriterion("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(Integer value) {
			addCriterion("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
			addCriterion("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<Integer> values) {
			addCriterion("task_id in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<Integer> values) {
			addCriterion("task_id not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(Integer value1, Integer value2) {
			addCriterion("task_id between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
			addCriterion("task_id not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Boolean value) {
			addCriterion("type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Boolean value) {
			addCriterion("type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Boolean value) {
			addCriterion("type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Boolean value) {
			addCriterion("type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Boolean> values) {
			addCriterion("type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Boolean> values) {
			addCriterion("type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andIsCheckIsNull() {
			addCriterion("is_check is null");
			return (Criteria) this;
		}

		public Criteria andIsCheckIsNotNull() {
			addCriterion("is_check is not null");
			return (Criteria) this;
		}

		public Criteria andIsCheckEqualTo(Boolean value) {
			addCriterion("is_check =", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckNotEqualTo(Boolean value) {
			addCriterion("is_check <>", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckGreaterThan(Boolean value) {
			addCriterion("is_check >", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckGreaterThanOrEqualTo(Boolean value) {
			addCriterion("is_check >=", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckLessThan(Boolean value) {
			addCriterion("is_check <", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckLessThanOrEqualTo(Boolean value) {
			addCriterion("is_check <=", value, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckIn(List<Boolean> values) {
			addCriterion("is_check in", values, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckNotIn(List<Boolean> values) {
			addCriterion("is_check not in", values, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckBetween(Boolean value1, Boolean value2) {
			addCriterion("is_check between", value1, value2, "isCheck");
			return (Criteria) this;
		}

		public Criteria andIsCheckNotBetween(Boolean value1, Boolean value2) {
			addCriterion("is_check not between", value1, value2, "isCheck");
			return (Criteria) this;
		}

		public Criteria andTimesNumIsNull() {
			addCriterion("times_num is null");
			return (Criteria) this;
		}

		public Criteria andTimesNumIsNotNull() {
			addCriterion("times_num is not null");
			return (Criteria) this;
		}

		public Criteria andTimesNumEqualTo(Integer value) {
			addCriterion("times_num =", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumNotEqualTo(Integer value) {
			addCriterion("times_num <>", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumGreaterThan(Integer value) {
			addCriterion("times_num >", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumGreaterThanOrEqualTo(Integer value) {
			addCriterion("times_num >=", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumLessThan(Integer value) {
			addCriterion("times_num <", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumLessThanOrEqualTo(Integer value) {
			addCriterion("times_num <=", value, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumIn(List<Integer> values) {
			addCriterion("times_num in", values, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumNotIn(List<Integer> values) {
			addCriterion("times_num not in", values, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumBetween(Integer value1, Integer value2) {
			addCriterion("times_num between", value1, value2, "timesNum");
			return (Criteria) this;
		}

		public Criteria andTimesNumNotBetween(Integer value1, Integer value2) {
			addCriterion("times_num not between", value1, value2, "timesNum");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNull() {
			addCriterion("category_id is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIsNotNull() {
			addCriterion("category_id is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryIdEqualTo(Integer value) {
			addCriterion("category_id =", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotEqualTo(Integer value) {
			addCriterion("category_id <>", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThan(Integer value) {
			addCriterion("category_id >", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("category_id >=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThan(Integer value) {
			addCriterion("category_id <", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdLessThanOrEqualTo(Integer value) {
			addCriterion("category_id <=", value, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdIn(List<Integer> values) {
			addCriterion("category_id in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotIn(List<Integer> values) {
			addCriterion("category_id not in", values, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdBetween(Integer value1, Integer value2) {
			addCriterion("category_id between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCategoryIdNotBetween(Integer value1, Integer value2) {
			addCriterion("category_id not between", value1, value2, "categoryId");
			return (Criteria) this;
		}

		public Criteria andCardPreIsNull() {
			addCriterion("card_pre is null");
			return (Criteria) this;
		}

		public Criteria andCardPreIsNotNull() {
			addCriterion("card_pre is not null");
			return (Criteria) this;
		}

		public Criteria andCardPreEqualTo(String value) {
			addCriterion("card_pre =", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreNotEqualTo(String value) {
			addCriterion("card_pre <>", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreGreaterThan(String value) {
			addCriterion("card_pre >", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreGreaterThanOrEqualTo(String value) {
			addCriterion("card_pre >=", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreLessThan(String value) {
			addCriterion("card_pre <", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreLessThanOrEqualTo(String value) {
			addCriterion("card_pre <=", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreLike(String value) {
			addCriterion("card_pre like", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreNotLike(String value) {
			addCriterion("card_pre not like", value, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreIn(List<String> values) {
			addCriterion("card_pre in", values, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreNotIn(List<String> values) {
			addCriterion("card_pre not in", values, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreBetween(String value1, String value2) {
			addCriterion("card_pre between", value1, value2, "cardPre");
			return (Criteria) this;
		}

		public Criteria andCardPreNotBetween(String value1, String value2) {
			addCriterion("card_pre not between", value1, value2, "cardPre");
			return (Criteria) this;
		}

		public Criteria andUseConditionIsNull() {
			addCriterion("use_condition is null");
			return (Criteria) this;
		}

		public Criteria andUseConditionIsNotNull() {
			addCriterion("use_condition is not null");
			return (Criteria) this;
		}

		public Criteria andUseConditionEqualTo(BigDecimal value) {
			addCriterion("use_condition =", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotEqualTo(BigDecimal value) {
			addCriterion("use_condition <>", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionGreaterThan(BigDecimal value) {
			addCriterion("use_condition >", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("use_condition >=", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionLessThan(BigDecimal value) {
			addCriterion("use_condition <", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionLessThanOrEqualTo(BigDecimal value) {
			addCriterion("use_condition <=", value, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionIn(List<BigDecimal> values) {
			addCriterion("use_condition in", values, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotIn(List<BigDecimal> values) {
			addCriterion("use_condition not in", values, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("use_condition between", value1, value2, "useCondition");
			return (Criteria) this;
		}

		public Criteria andUseConditionNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("use_condition not between", value1, value2, "useCondition");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(BigDecimal value) {
			addCriterion("money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(BigDecimal value) {
			addCriterion("money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(BigDecimal value) {
			addCriterion("money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(BigDecimal value) {
			addCriterion("money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<BigDecimal> values) {
			addCriterion("money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<BigDecimal> values) {
			addCriterion("money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIsNull() {
			addCriterion("validity_period_type is null");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIsNotNull() {
			addCriterion("validity_period_type is not null");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeEqualTo(Boolean value) {
			addCriterion("validity_period_type =", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotEqualTo(Boolean value) {
			addCriterion("validity_period_type <>", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeGreaterThan(Boolean value) {
			addCriterion("validity_period_type >", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("validity_period_type >=", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeLessThan(Boolean value) {
			addCriterion("validity_period_type <", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeLessThanOrEqualTo(Boolean value) {
			addCriterion("validity_period_type <=", value, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeIn(List<Boolean> values) {
			addCriterion("validity_period_type in", values, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotIn(List<Boolean> values) {
			addCriterion("validity_period_type not in", values, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeBetween(Boolean value1, Boolean value2) {
			addCriterion("validity_period_type between", value1, value2, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andValidityPeriodTypeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("validity_period_type not between", value1, value2, "validityPeriodType");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNull() {
			addCriterion("start_date is null");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNotNull() {
			addCriterion("start_date is not null");
			return (Criteria) this;
		}

		public Criteria andStartDateEqualTo(Integer value) {
			addCriterion("start_date =", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotEqualTo(Integer value) {
			addCriterion("start_date <>", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThan(Integer value) {
			addCriterion("start_date >", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThanOrEqualTo(Integer value) {
			addCriterion("start_date >=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThan(Integer value) {
			addCriterion("start_date <", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThanOrEqualTo(Integer value) {
			addCriterion("start_date <=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIn(List<Integer> values) {
			addCriterion("start_date in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotIn(List<Integer> values) {
			addCriterion("start_date not in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateBetween(Integer value1, Integer value2) {
			addCriterion("start_date between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotBetween(Integer value1, Integer value2) {
			addCriterion("start_date not between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andDueDateIsNull() {
			addCriterion("due_date is null");
			return (Criteria) this;
		}

		public Criteria andDueDateIsNotNull() {
			addCriterion("due_date is not null");
			return (Criteria) this;
		}

		public Criteria andDueDateEqualTo(Integer value) {
			addCriterion("due_date =", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotEqualTo(Integer value) {
			addCriterion("due_date <>", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateGreaterThan(Integer value) {
			addCriterion("due_date >", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateGreaterThanOrEqualTo(Integer value) {
			addCriterion("due_date >=", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateLessThan(Integer value) {
			addCriterion("due_date <", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateLessThanOrEqualTo(Integer value) {
			addCriterion("due_date <=", value, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateIn(List<Integer> values) {
			addCriterion("due_date in", values, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotIn(List<Integer> values) {
			addCriterion("due_date not in", values, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateBetween(Integer value1, Integer value2) {
			addCriterion("due_date between", value1, value2, "dueDate");
			return (Criteria) this;
		}

		public Criteria andDueDateNotBetween(Integer value1, Integer value2) {
			addCriterion("due_date not between", value1, value2, "dueDate");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNull() {
			addCriterion("valid_time is null");
			return (Criteria) this;
		}

		public Criteria andValidTimeIsNotNull() {
			addCriterion("valid_time is not null");
			return (Criteria) this;
		}

		public Criteria andValidTimeEqualTo(Integer value) {
			addCriterion("valid_time =", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotEqualTo(Integer value) {
			addCriterion("valid_time <>", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThan(Integer value) {
			addCriterion("valid_time >", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("valid_time >=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThan(Integer value) {
			addCriterion("valid_time <", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeLessThanOrEqualTo(Integer value) {
			addCriterion("valid_time <=", value, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeIn(List<Integer> values) {
			addCriterion("valid_time in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotIn(List<Integer> values) {
			addCriterion("valid_time not in", values, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeBetween(Integer value1, Integer value2) {
			addCriterion("valid_time between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andValidTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("valid_time not between", value1, value2, "validTime");
			return (Criteria) this;
		}

		public Criteria andNumsIsNull() {
			addCriterion("nums is null");
			return (Criteria) this;
		}

		public Criteria andNumsIsNotNull() {
			addCriterion("nums is not null");
			return (Criteria) this;
		}

		public Criteria andNumsEqualTo(Integer value) {
			addCriterion("nums =", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotEqualTo(Integer value) {
			addCriterion("nums <>", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsGreaterThan(Integer value) {
			addCriterion("nums >", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsGreaterThanOrEqualTo(Integer value) {
			addCriterion("nums >=", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsLessThan(Integer value) {
			addCriterion("nums <", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsLessThanOrEqualTo(Integer value) {
			addCriterion("nums <=", value, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsIn(List<Integer> values) {
			addCriterion("nums in", values, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotIn(List<Integer> values) {
			addCriterion("nums not in", values, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsBetween(Integer value1, Integer value2) {
			addCriterion("nums between", value1, value2, "nums");
			return (Criteria) this;
		}

		public Criteria andNumsNotBetween(Integer value1, Integer value2) {
			addCriterion("nums not between", value1, value2, "nums");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNull() {
			addCriterion("create_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIsNotNull() {
			addCriterion("create_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdEqualTo(Integer value) {
			addCriterion("create_user_id =", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotEqualTo(Integer value) {
			addCriterion("create_user_id <>", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThan(Integer value) {
			addCriterion("create_user_id >", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_user_id >=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThan(Integer value) {
			addCriterion("create_user_id <", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("create_user_id <=", value, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdIn(List<Integer> values) {
			addCriterion("create_user_id in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotIn(List<Integer> values) {
			addCriterion("create_user_id not in", values, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andCreateUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("create_user_id not between", value1, value2, "createUserId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCardStatusIsNull() {
			addCriterion("card_status is null");
			return (Criteria) this;
		}

		public Criteria andCardStatusIsNotNull() {
			addCriterion("card_status is not null");
			return (Criteria) this;
		}

		public Criteria andCardStatusEqualTo(Integer value) {
			addCriterion("card_status =", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusNotEqualTo(Integer value) {
			addCriterion("card_status <>", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusGreaterThan(Integer value) {
			addCriterion("card_status >", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("card_status >=", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusLessThan(Integer value) {
			addCriterion("card_status <", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusLessThanOrEqualTo(Integer value) {
			addCriterion("card_status <=", value, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusIn(List<Integer> values) {
			addCriterion("card_status in", values, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusNotIn(List<Integer> values) {
			addCriterion("card_status not in", values, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusBetween(Integer value1, Integer value2) {
			addCriterion("card_status between", value1, value2, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andCardStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("card_status not between", value1, value2, "cardStatus");
			return (Criteria) this;
		}

		public Criteria andUseObjectIsNull() {
			addCriterion("use_object is null");
			return (Criteria) this;
		}

		public Criteria andUseObjectIsNotNull() {
			addCriterion("use_object is not null");
			return (Criteria) this;
		}

		public Criteria andUseObjectEqualTo(String value) {
			addCriterion("use_object =", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectNotEqualTo(String value) {
			addCriterion("use_object <>", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectGreaterThan(String value) {
			addCriterion("use_object >", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectGreaterThanOrEqualTo(String value) {
			addCriterion("use_object >=", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectLessThan(String value) {
			addCriterion("use_object <", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectLessThanOrEqualTo(String value) {
			addCriterion("use_object <=", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectLike(String value) {
			addCriterion("use_object like", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectNotLike(String value) {
			addCriterion("use_object not like", value, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectIn(List<String> values) {
			addCriterion("use_object in", values, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectNotIn(List<String> values) {
			addCriterion("use_object not in", values, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectBetween(String value1, String value2) {
			addCriterion("use_object between", value1, value2, "useObject");
			return (Criteria) this;
		}

		public Criteria andUseObjectNotBetween(String value1, String value2) {
			addCriterion("use_object not between", value1, value2, "useObject");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdIsNull() {
			addCriterion("check_user_id is null");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdIsNotNull() {
			addCriterion("check_user_id is not null");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdEqualTo(Integer value) {
			addCriterion("check_user_id =", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdNotEqualTo(Integer value) {
			addCriterion("check_user_id <>", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdGreaterThan(Integer value) {
			addCriterion("check_user_id >", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("check_user_id >=", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdLessThan(Integer value) {
			addCriterion("check_user_id <", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdLessThanOrEqualTo(Integer value) {
			addCriterion("check_user_id <=", value, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdIn(List<Integer> values) {
			addCriterion("check_user_id in", values, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdNotIn(List<Integer> values) {
			addCriterion("check_user_id not in", values, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdBetween(Integer value1, Integer value2) {
			addCriterion("check_user_id between", value1, value2, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andCheckUserIdNotBetween(Integer value1, Integer value2) {
			addCriterion("check_user_id not between", value1, value2, "checkUserId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNull() {
			addCriterion("channel_id is null");
			return (Criteria) this;
		}

		public Criteria andChannelIdIsNotNull() {
			addCriterion("channel_id is not null");
			return (Criteria) this;
		}

		public Criteria andChannelIdEqualTo(Integer value) {
			addCriterion("channel_id =", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotEqualTo(Integer value) {
			addCriterion("channel_id <>", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThan(Integer value) {
			addCriterion("channel_id >", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("channel_id >=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThan(Integer value) {
			addCriterion("channel_id <", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdLessThanOrEqualTo(Integer value) {
			addCriterion("channel_id <=", value, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdIn(List<Integer> values) {
			addCriterion("channel_id in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotIn(List<Integer> values) {
			addCriterion("channel_id not in", values, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdBetween(Integer value1, Integer value2) {
			addCriterion("channel_id between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andChannelIdNotBetween(Integer value1, Integer value2) {
			addCriterion("channel_id not between", value1, value2, "channelId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Integer value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Integer value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Integer value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Integer value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Integer value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Integer> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Integer> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Integer value1, Integer value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIsNull() {
			addCriterion("effective_time is null");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIsNotNull() {
			addCriterion("effective_time is not null");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeEqualTo(Integer value) {
			addCriterion("effective_time =", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotEqualTo(Integer value) {
			addCriterion("effective_time <>", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeGreaterThan(Integer value) {
			addCriterion("effective_time >", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("effective_time >=", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeLessThan(Integer value) {
			addCriterion("effective_time <", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeLessThanOrEqualTo(Integer value) {
			addCriterion("effective_time <=", value, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeIn(List<Integer> values) {
			addCriterion("effective_time in", values, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotIn(List<Integer> values) {
			addCriterion("effective_time not in", values, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeBetween(Integer value1, Integer value2) {
			addCriterion("effective_time between", value1, value2, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andEffectiveTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("effective_time not between", value1, value2, "effectiveTime");
			return (Criteria) this;
		}

		public Criteria andChannelUserIsNull() {
			addCriterion("channel_user is null");
			return (Criteria) this;
		}

		public Criteria andChannelUserIsNotNull() {
			addCriterion("channel_user is not null");
			return (Criteria) this;
		}

		public Criteria andChannelUserEqualTo(String value) {
			addCriterion("channel_user =", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotEqualTo(String value) {
			addCriterion("channel_user <>", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserGreaterThan(String value) {
			addCriterion("channel_user >", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserGreaterThanOrEqualTo(String value) {
			addCriterion("channel_user >=", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLessThan(String value) {
			addCriterion("channel_user <", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLessThanOrEqualTo(String value) {
			addCriterion("channel_user <=", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserLike(String value) {
			addCriterion("channel_user like", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotLike(String value) {
			addCriterion("channel_user not like", value, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserIn(List<String> values) {
			addCriterion("channel_user in", values, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotIn(List<String> values) {
			addCriterion("channel_user not in", values, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserBetween(String value1, String value2) {
			addCriterion("channel_user between", value1, value2, "channelUser");
			return (Criteria) this;
		}

		public Criteria andChannelUserNotBetween(String value1, String value2) {
			addCriterion("channel_user not between", value1, value2, "channelUser");
			return (Criteria) this;
		}

		public Criteria andScopeIsNull() {
			addCriterion("scope is null");
			return (Criteria) this;
		}

		public Criteria andScopeIsNotNull() {
			addCriterion("scope is not null");
			return (Criteria) this;
		}

		public Criteria andScopeEqualTo(Boolean value) {
			addCriterion("scope =", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotEqualTo(Boolean value) {
			addCriterion("scope <>", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeGreaterThan(Boolean value) {
			addCriterion("scope >", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeGreaterThanOrEqualTo(Boolean value) {
			addCriterion("scope >=", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeLessThan(Boolean value) {
			addCriterion("scope <", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeLessThanOrEqualTo(Boolean value) {
			addCriterion("scope <=", value, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeIn(List<Boolean> values) {
			addCriterion("scope in", values, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotIn(List<Boolean> values) {
			addCriterion("scope not in", values, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeBetween(Boolean value1, Boolean value2) {
			addCriterion("scope between", value1, value2, "scope");
			return (Criteria) this;
		}

		public Criteria andScopeNotBetween(Boolean value1, Boolean value2) {
			addCriterion("scope not between", value1, value2, "scope");
			return (Criteria) this;
		}

		public Criteria andCardTypeIsNull() {
			addCriterion("card_type is null");
			return (Criteria) this;
		}

		public Criteria andCardTypeIsNotNull() {
			addCriterion("card_type is not null");
			return (Criteria) this;
		}

		public Criteria andCardTypeEqualTo(Integer value) {
			addCriterion("card_type =", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotEqualTo(Integer value) {
			addCriterion("card_type <>", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeGreaterThan(Integer value) {
			addCriterion("card_type >", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("card_type >=", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeLessThan(Integer value) {
			addCriterion("card_type <", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeLessThanOrEqualTo(Integer value) {
			addCriterion("card_type <=", value, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeIn(List<Integer> values) {
			addCriterion("card_type in", values, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotIn(List<Integer> values) {
			addCriterion("card_type not in", values, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeBetween(Integer value1, Integer value2) {
			addCriterion("card_type between", value1, value2, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("card_type not between", value1, value2, "cardType");
			return (Criteria) this;
		}

		public Criteria andCardNumIsNull() {
			addCriterion("card_num is null");
			return (Criteria) this;
		}

		public Criteria andCardNumIsNotNull() {
			addCriterion("card_num is not null");
			return (Criteria) this;
		}

		public Criteria andCardNumEqualTo(String value) {
			addCriterion("card_num =", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumNotEqualTo(String value) {
			addCriterion("card_num <>", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumGreaterThan(String value) {
			addCriterion("card_num >", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumGreaterThanOrEqualTo(String value) {
			addCriterion("card_num >=", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumLessThan(String value) {
			addCriterion("card_num <", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumLessThanOrEqualTo(String value) {
			addCriterion("card_num <=", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumLike(String value) {
			addCriterion("card_num like", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumNotLike(String value) {
			addCriterion("card_num not like", value, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumIn(List<String> values) {
			addCriterion("card_num in", values, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumNotIn(List<String> values) {
			addCriterion("card_num not in", values, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumBetween(String value1, String value2) {
			addCriterion("card_num between", value1, value2, "cardNum");
			return (Criteria) this;
		}

		public Criteria andCardNumNotBetween(String value1, String value2) {
			addCriterion("card_num not between", value1, value2, "cardNum");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIsNull() {
			addCriterion("use_range_detail is null");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIsNotNull() {
			addCriterion("use_range_detail is not null");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailEqualTo(String value) {
			addCriterion("use_range_detail =", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotEqualTo(String value) {
			addCriterion("use_range_detail <>", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailGreaterThan(String value) {
			addCriterion("use_range_detail >", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailGreaterThanOrEqualTo(String value) {
			addCriterion("use_range_detail >=", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLessThan(String value) {
			addCriterion("use_range_detail <", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLessThanOrEqualTo(String value) {
			addCriterion("use_range_detail <=", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailLike(String value) {
			addCriterion("use_range_detail like", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotLike(String value) {
			addCriterion("use_range_detail not like", value, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailIn(List<String> values) {
			addCriterion("use_range_detail in", values, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotIn(List<String> values) {
			addCriterion("use_range_detail not in", values, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailBetween(String value1, String value2) {
			addCriterion("use_range_detail between", value1, value2, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseRangeDetailNotBetween(String value1, String value2) {
			addCriterion("use_range_detail not between", value1, value2, "useRangeDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIsNull() {
			addCriterion("use_condition_detail is null");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIsNotNull() {
			addCriterion("use_condition_detail is not null");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailEqualTo(String value) {
			addCriterion("use_condition_detail =", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotEqualTo(String value) {
			addCriterion("use_condition_detail <>", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailGreaterThan(String value) {
			addCriterion("use_condition_detail >", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailGreaterThanOrEqualTo(String value) {
			addCriterion("use_condition_detail >=", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLessThan(String value) {
			addCriterion("use_condition_detail <", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLessThanOrEqualTo(String value) {
			addCriterion("use_condition_detail <=", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailLike(String value) {
			addCriterion("use_condition_detail like", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotLike(String value) {
			addCriterion("use_condition_detail not like", value, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailIn(List<String> values) {
			addCriterion("use_condition_detail in", values, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotIn(List<String> values) {
			addCriterion("use_condition_detail not in", values, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailBetween(String value1, String value2) {
			addCriterion("use_condition_detail between", value1, value2, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andUseConditionDetailNotBetween(String value1, String value2) {
			addCriterion("use_condition_detail not between", value1, value2, "useConditionDetail");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNull() {
			addCriterion("brand_id is null");
			return (Criteria) this;
		}

		public Criteria andBrandIdIsNotNull() {
			addCriterion("brand_id is not null");
			return (Criteria) this;
		}

		public Criteria andBrandIdEqualTo(Integer value) {
			addCriterion("brand_id =", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotEqualTo(Integer value) {
			addCriterion("brand_id <>", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThan(Integer value) {
			addCriterion("brand_id >", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("brand_id >=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThan(Integer value) {
			addCriterion("brand_id <", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
			addCriterion("brand_id <=", value, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdIn(List<Integer> values) {
			addCriterion("brand_id in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotIn(List<Integer> values) {
			addCriterion("brand_id not in", values, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdBetween(Integer value1, Integer value2) {
			addCriterion("brand_id between", value1, value2, "brandId");
			return (Criteria) this;
		}

		public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
			addCriterion("brand_id not between", value1, value2, "brandId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated do_not_delete_during_merge Fri Apr 01 20:18:53 CST 2016
	 */
	public static class Criteria extends GeneratedCriteria {

		protected Criteria() {
			super();
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to
	 * the database table gt_coupon_card_task
	 *
	 * @mbggenerated Fri Apr 01 20:18:53 CST 2016
	 */
	public static class Criterion {
		private String condition;

		private Object value;

		private Object secondValue;

		private boolean noValue;

		private boolean singleValue;

		private boolean betweenValue;

		private boolean listValue;

		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}
}