package com.zpapi.other.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class UcMembersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public UcMembersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Long value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Long value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Long value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Long value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Long value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Long value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Long> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Long> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Long value1, Long value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Long value1, Long value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andCurLevelIsNull() {
            addCriterion("cur_level is null");
            return (Criteria) this;
        }

        public Criteria andCurLevelIsNotNull() {
            addCriterion("cur_level is not null");
            return (Criteria) this;
        }

        public Criteria andCurLevelEqualTo(Integer value) {
            addCriterion("cur_level =", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelNotEqualTo(Integer value) {
            addCriterion("cur_level <>", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelGreaterThan(Integer value) {
            addCriterion("cur_level >", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("cur_level >=", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelLessThan(Integer value) {
            addCriterion("cur_level <", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelLessThanOrEqualTo(Integer value) {
            addCriterion("cur_level <=", value, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelIn(List<Integer> values) {
            addCriterion("cur_level in", values, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelNotIn(List<Integer> values) {
            addCriterion("cur_level not in", values, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelBetween(Integer value1, Integer value2) {
            addCriterion("cur_level between", value1, value2, "curLevel");
            return (Criteria) this;
        }

        public Criteria andCurLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("cur_level not between", value1, value2, "curLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelIsNull() {
            addCriterion("top_level is null");
            return (Criteria) this;
        }

        public Criteria andTopLevelIsNotNull() {
            addCriterion("top_level is not null");
            return (Criteria) this;
        }

        public Criteria andTopLevelEqualTo(Integer value) {
            addCriterion("top_level =", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelNotEqualTo(Integer value) {
            addCriterion("top_level <>", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelGreaterThan(Integer value) {
            addCriterion("top_level >", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelGreaterThanOrEqualTo(Integer value) {
            addCriterion("top_level >=", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelLessThan(Integer value) {
            addCriterion("top_level <", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelLessThanOrEqualTo(Integer value) {
            addCriterion("top_level <=", value, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelIn(List<Integer> values) {
            addCriterion("top_level in", values, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelNotIn(List<Integer> values) {
            addCriterion("top_level not in", values, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelBetween(Integer value1, Integer value2) {
            addCriterion("top_level between", value1, value2, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTopLevelNotBetween(Integer value1, Integer value2) {
            addCriterion("top_level not between", value1, value2, "topLevel");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionIsNull() {
            addCriterion("total_consumption is null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionIsNotNull() {
            addCriterion("total_consumption is not null");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionEqualTo(BigDecimal value) {
            addCriterion("total_consumption =", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionNotEqualTo(BigDecimal value) {
            addCriterion("total_consumption <>", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionGreaterThan(BigDecimal value) {
            addCriterion("total_consumption >", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_consumption >=", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionLessThan(BigDecimal value) {
            addCriterion("total_consumption <", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_consumption <=", value, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionIn(List<BigDecimal> values) {
            addCriterion("total_consumption in", values, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionNotIn(List<BigDecimal> values) {
            addCriterion("total_consumption not in", values, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_consumption between", value1, value2, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andTotalConsumptionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_consumption not between", value1, value2, "totalConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionIsNull() {
            addCriterion("active_consumption is null");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionIsNotNull() {
            addCriterion("active_consumption is not null");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionEqualTo(BigDecimal value) {
            addCriterion("active_consumption =", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionNotEqualTo(BigDecimal value) {
            addCriterion("active_consumption <>", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionGreaterThan(BigDecimal value) {
            addCriterion("active_consumption >", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("active_consumption >=", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionLessThan(BigDecimal value) {
            addCriterion("active_consumption <", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionLessThanOrEqualTo(BigDecimal value) {
            addCriterion("active_consumption <=", value, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionIn(List<BigDecimal> values) {
            addCriterion("active_consumption in", values, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionNotIn(List<BigDecimal> values) {
            addCriterion("active_consumption not in", values, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("active_consumption between", value1, value2, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andActiveConsumptionNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("active_consumption not between", value1, value2, "activeConsumption");
            return (Criteria) this;
        }

        public Criteria andMyidIsNull() {
            addCriterion("myid is null");
            return (Criteria) this;
        }

        public Criteria andMyidIsNotNull() {
            addCriterion("myid is not null");
            return (Criteria) this;
        }

        public Criteria andMyidEqualTo(String value) {
            addCriterion("myid =", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidNotEqualTo(String value) {
            addCriterion("myid <>", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidGreaterThan(String value) {
            addCriterion("myid >", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidGreaterThanOrEqualTo(String value) {
            addCriterion("myid >=", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidLessThan(String value) {
            addCriterion("myid <", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidLessThanOrEqualTo(String value) {
            addCriterion("myid <=", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidLike(String value) {
            addCriterion("myid like", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidNotLike(String value) {
            addCriterion("myid not like", value, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidIn(List<String> values) {
            addCriterion("myid in", values, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidNotIn(List<String> values) {
            addCriterion("myid not in", values, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidBetween(String value1, String value2) {
            addCriterion("myid between", value1, value2, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidNotBetween(String value1, String value2) {
            addCriterion("myid not between", value1, value2, "myid");
            return (Criteria) this;
        }

        public Criteria andMyidkeyIsNull() {
            addCriterion("myidkey is null");
            return (Criteria) this;
        }

        public Criteria andMyidkeyIsNotNull() {
            addCriterion("myidkey is not null");
            return (Criteria) this;
        }

        public Criteria andMyidkeyEqualTo(String value) {
            addCriterion("myidkey =", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyNotEqualTo(String value) {
            addCriterion("myidkey <>", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyGreaterThan(String value) {
            addCriterion("myidkey >", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyGreaterThanOrEqualTo(String value) {
            addCriterion("myidkey >=", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyLessThan(String value) {
            addCriterion("myidkey <", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyLessThanOrEqualTo(String value) {
            addCriterion("myidkey <=", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyLike(String value) {
            addCriterion("myidkey like", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyNotLike(String value) {
            addCriterion("myidkey not like", value, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyIn(List<String> values) {
            addCriterion("myidkey in", values, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyNotIn(List<String> values) {
            addCriterion("myidkey not in", values, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyBetween(String value1, String value2) {
            addCriterion("myidkey between", value1, value2, "myidkey");
            return (Criteria) this;
        }

        public Criteria andMyidkeyNotBetween(String value1, String value2) {
            addCriterion("myidkey not between", value1, value2, "myidkey");
            return (Criteria) this;
        }

        public Criteria andRegipIsNull() {
            addCriterion("regip is null");
            return (Criteria) this;
        }

        public Criteria andRegipIsNotNull() {
            addCriterion("regip is not null");
            return (Criteria) this;
        }

        public Criteria andRegipEqualTo(String value) {
            addCriterion("regip =", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotEqualTo(String value) {
            addCriterion("regip <>", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipGreaterThan(String value) {
            addCriterion("regip >", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipGreaterThanOrEqualTo(String value) {
            addCriterion("regip >=", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipLessThan(String value) {
            addCriterion("regip <", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipLessThanOrEqualTo(String value) {
            addCriterion("regip <=", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipLike(String value) {
            addCriterion("regip like", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotLike(String value) {
            addCriterion("regip not like", value, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipIn(List<String> values) {
            addCriterion("regip in", values, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotIn(List<String> values) {
            addCriterion("regip not in", values, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipBetween(String value1, String value2) {
            addCriterion("regip between", value1, value2, "regip");
            return (Criteria) this;
        }

        public Criteria andRegipNotBetween(String value1, String value2) {
            addCriterion("regip not between", value1, value2, "regip");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNull() {
            addCriterion("regdate is null");
            return (Criteria) this;
        }

        public Criteria andRegdateIsNotNull() {
            addCriterion("regdate is not null");
            return (Criteria) this;
        }

        public Criteria andRegdateEqualTo(Integer value) {
            addCriterion("regdate =", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotEqualTo(Integer value) {
            addCriterion("regdate <>", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThan(Integer value) {
            addCriterion("regdate >", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateGreaterThanOrEqualTo(Integer value) {
            addCriterion("regdate >=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThan(Integer value) {
            addCriterion("regdate <", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateLessThanOrEqualTo(Integer value) {
            addCriterion("regdate <=", value, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateIn(List<Integer> values) {
            addCriterion("regdate in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotIn(List<Integer> values) {
            addCriterion("regdate not in", values, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateBetween(Integer value1, Integer value2) {
            addCriterion("regdate between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andRegdateNotBetween(Integer value1, Integer value2) {
            addCriterion("regdate not between", value1, value2, "regdate");
            return (Criteria) this;
        }

        public Criteria andLastloginipIsNull() {
            addCriterion("lastloginip is null");
            return (Criteria) this;
        }

        public Criteria andLastloginipIsNotNull() {
            addCriterion("lastloginip is not null");
            return (Criteria) this;
        }

        public Criteria andLastloginipEqualTo(Integer value) {
            addCriterion("lastloginip =", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipNotEqualTo(Integer value) {
            addCriterion("lastloginip <>", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipGreaterThan(Integer value) {
            addCriterion("lastloginip >", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastloginip >=", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipLessThan(Integer value) {
            addCriterion("lastloginip <", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipLessThanOrEqualTo(Integer value) {
            addCriterion("lastloginip <=", value, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipIn(List<Integer> values) {
            addCriterion("lastloginip in", values, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipNotIn(List<Integer> values) {
            addCriterion("lastloginip not in", values, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipBetween(Integer value1, Integer value2) {
            addCriterion("lastloginip between", value1, value2, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastloginipNotBetween(Integer value1, Integer value2) {
            addCriterion("lastloginip not between", value1, value2, "lastloginip");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNull() {
            addCriterion("lastlogintime is null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIsNotNull() {
            addCriterion("lastlogintime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeEqualTo(Integer value) {
            addCriterion("lastlogintime =", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotEqualTo(Integer value) {
            addCriterion("lastlogintime <>", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThan(Integer value) {
            addCriterion("lastlogintime >", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("lastlogintime >=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThan(Integer value) {
            addCriterion("lastlogintime <", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeLessThanOrEqualTo(Integer value) {
            addCriterion("lastlogintime <=", value, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeIn(List<Integer> values) {
            addCriterion("lastlogintime in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotIn(List<Integer> values) {
            addCriterion("lastlogintime not in", values, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeBetween(Integer value1, Integer value2) {
            addCriterion("lastlogintime between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andLastlogintimeNotBetween(Integer value1, Integer value2) {
            addCriterion("lastlogintime not between", value1, value2, "lastlogintime");
            return (Criteria) this;
        }

        public Criteria andSaltIsNull() {
            addCriterion("salt is null");
            return (Criteria) this;
        }

        public Criteria andSaltIsNotNull() {
            addCriterion("salt is not null");
            return (Criteria) this;
        }

        public Criteria andSaltEqualTo(String value) {
            addCriterion("salt =", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotEqualTo(String value) {
            addCriterion("salt <>", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThan(String value) {
            addCriterion("salt >", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltGreaterThanOrEqualTo(String value) {
            addCriterion("salt >=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThan(String value) {
            addCriterion("salt <", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLessThanOrEqualTo(String value) {
            addCriterion("salt <=", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltLike(String value) {
            addCriterion("salt like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotLike(String value) {
            addCriterion("salt not like", value, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltIn(List<String> values) {
            addCriterion("salt in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotIn(List<String> values) {
            addCriterion("salt not in", values, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltBetween(String value1, String value2) {
            addCriterion("salt between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSaltNotBetween(String value1, String value2) {
            addCriterion("salt not between", value1, value2, "salt");
            return (Criteria) this;
        }

        public Criteria andSecquesIsNull() {
            addCriterion("secques is null");
            return (Criteria) this;
        }

        public Criteria andSecquesIsNotNull() {
            addCriterion("secques is not null");
            return (Criteria) this;
        }

        public Criteria andSecquesEqualTo(String value) {
            addCriterion("secques =", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesNotEqualTo(String value) {
            addCriterion("secques <>", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesGreaterThan(String value) {
            addCriterion("secques >", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesGreaterThanOrEqualTo(String value) {
            addCriterion("secques >=", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesLessThan(String value) {
            addCriterion("secques <", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesLessThanOrEqualTo(String value) {
            addCriterion("secques <=", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesLike(String value) {
            addCriterion("secques like", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesNotLike(String value) {
            addCriterion("secques not like", value, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesIn(List<String> values) {
            addCriterion("secques in", values, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesNotIn(List<String> values) {
            addCriterion("secques not in", values, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesBetween(String value1, String value2) {
            addCriterion("secques between", value1, value2, "secques");
            return (Criteria) this;
        }

        public Criteria andSecquesNotBetween(String value1, String value2) {
            addCriterion("secques not between", value1, value2, "secques");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumIsNull() {
            addCriterion("login_error_num is null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumIsNotNull() {
            addCriterion("login_error_num is not null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumEqualTo(Integer value) {
            addCriterion("login_error_num =", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumNotEqualTo(Integer value) {
            addCriterion("login_error_num <>", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumGreaterThan(Integer value) {
            addCriterion("login_error_num >", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_error_num >=", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumLessThan(Integer value) {
            addCriterion("login_error_num <", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumLessThanOrEqualTo(Integer value) {
            addCriterion("login_error_num <=", value, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumIn(List<Integer> values) {
            addCriterion("login_error_num in", values, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumNotIn(List<Integer> values) {
            addCriterion("login_error_num not in", values, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumBetween(Integer value1, Integer value2) {
            addCriterion("login_error_num between", value1, value2, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorNumNotBetween(Integer value1, Integer value2) {
            addCriterion("login_error_num not between", value1, value2, "loginErrorNum");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeIsNull() {
            addCriterion("login_error_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeIsNotNull() {
            addCriterion("login_error_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeEqualTo(Integer value) {
            addCriterion("login_error_time =", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeNotEqualTo(Integer value) {
            addCriterion("login_error_time <>", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeGreaterThan(Integer value) {
            addCriterion("login_error_time >", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_error_time >=", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeLessThan(Integer value) {
            addCriterion("login_error_time <", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeLessThanOrEqualTo(Integer value) {
            addCriterion("login_error_time <=", value, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeIn(List<Integer> values) {
            addCriterion("login_error_time in", values, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeNotIn(List<Integer> values) {
            addCriterion("login_error_time not in", values, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeBetween(Integer value1, Integer value2) {
            addCriterion("login_error_time between", value1, value2, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginErrorTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("login_error_time not between", value1, value2, "loginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeIsNull() {
            addCriterion("login_lock_time is null");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeIsNotNull() {
            addCriterion("login_lock_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeEqualTo(Integer value) {
            addCriterion("login_lock_time =", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeNotEqualTo(Integer value) {
            addCriterion("login_lock_time <>", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeGreaterThan(Integer value) {
            addCriterion("login_lock_time >", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("login_lock_time >=", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeLessThan(Integer value) {
            addCriterion("login_lock_time <", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeLessThanOrEqualTo(Integer value) {
            addCriterion("login_lock_time <=", value, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeIn(List<Integer> values) {
            addCriterion("login_lock_time in", values, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeNotIn(List<Integer> values) {
            addCriterion("login_lock_time not in", values, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeBetween(Integer value1, Integer value2) {
            addCriterion("login_lock_time between", value1, value2, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andLoginLockTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("login_lock_time not between", value1, value2, "loginLockTime");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdIsNull() {
            addCriterion("third_party_id is null");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdIsNotNull() {
            addCriterion("third_party_id is not null");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdEqualTo(String value) {
            addCriterion("third_party_id =", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdNotEqualTo(String value) {
            addCriterion("third_party_id <>", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdGreaterThan(String value) {
            addCriterion("third_party_id >", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdGreaterThanOrEqualTo(String value) {
            addCriterion("third_party_id >=", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdLessThan(String value) {
            addCriterion("third_party_id <", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdLessThanOrEqualTo(String value) {
            addCriterion("third_party_id <=", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdLike(String value) {
            addCriterion("third_party_id like", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdNotLike(String value) {
            addCriterion("third_party_id not like", value, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdIn(List<String> values) {
            addCriterion("third_party_id in", values, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdNotIn(List<String> values) {
            addCriterion("third_party_id not in", values, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdBetween(String value1, String value2) {
            addCriterion("third_party_id between", value1, value2, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andThirdPartyIdNotBetween(String value1, String value2) {
            addCriterion("third_party_id not between", value1, value2, "thirdPartyId");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("source like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("source not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andIsBondIsNull() {
            addCriterion("is_bond is null");
            return (Criteria) this;
        }

        public Criteria andIsBondIsNotNull() {
            addCriterion("is_bond is not null");
            return (Criteria) this;
        }

        public Criteria andIsBondEqualTo(Boolean value) {
            addCriterion("is_bond =", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondNotEqualTo(Boolean value) {
            addCriterion("is_bond <>", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondGreaterThan(Boolean value) {
            addCriterion("is_bond >", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_bond >=", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondLessThan(Boolean value) {
            addCriterion("is_bond <", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondLessThanOrEqualTo(Boolean value) {
            addCriterion("is_bond <=", value, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondIn(List<Boolean> values) {
            addCriterion("is_bond in", values, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondNotIn(List<Boolean> values) {
            addCriterion("is_bond not in", values, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bond between", value1, value2, "isBond");
            return (Criteria) this;
        }

        public Criteria andIsBondNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_bond not between", value1, value2, "isBond");
            return (Criteria) this;
        }

        public Criteria andChannelIsNull() {
            addCriterion("channel is null");
            return (Criteria) this;
        }

        public Criteria andChannelIsNotNull() {
            addCriterion("channel is not null");
            return (Criteria) this;
        }

        public Criteria andChannelEqualTo(String value) {
            addCriterion("channel =", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotEqualTo(String value) {
            addCriterion("channel <>", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThan(String value) {
            addCriterion("channel >", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelGreaterThanOrEqualTo(String value) {
            addCriterion("channel >=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThan(String value) {
            addCriterion("channel <", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLessThanOrEqualTo(String value) {
            addCriterion("channel <=", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelLike(String value) {
            addCriterion("channel like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotLike(String value) {
            addCriterion("channel not like", value, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelIn(List<String> values) {
            addCriterion("channel in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotIn(List<String> values) {
            addCriterion("channel not in", values, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelBetween(String value1, String value2) {
            addCriterion("channel between", value1, value2, "channel");
            return (Criteria) this;
        }

        public Criteria andChannelNotBetween(String value1, String value2) {
            addCriterion("channel not between", value1, value2, "channel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_members
     *
     * @mbggenerated do_not_delete_during_merge Fri Apr 01 19:47:31 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table uc_members
     *
     * @mbggenerated Fri Apr 01 19:47:31 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}